### ISSUE TITLE
pod bugly 解压zip 报错 怎么搞？ 

### ISSUE THREAD

**Issue by wff-** [BuglyDevTeam/Bugly-iOS#10]
![a373db5b-c9ad-4020-899e-6b8b52680f9d](https://user-images.githubusercontent.com/8870484/33425146-cd528e08-d5f8-11e7-9597-fd920943bfb6.png)

**Comment by Navimark** [comment]
+1

**Comment by Navimark** [comment]
+1

**Comment by Navimark** [comment]
+1
看起来是更新到 `2.5.0` 后才出现的问题，我指定版本为`2.4.8`就可以更新

**Comment by freezy7** [comment]
同样的问题，建议源放在国内啊，不要放在github上，这样下载就快多了不是

**Comment by CaffreySun** [comment]
+1

**Comment by iliYF** [comment]
可能跟Github仓库开启LFS设置有关，建议先指定2.4.8版本使用，我们尽快修复处理下载源的问题

**Comment by iliYF** [comment]
已经修改Github仓库的LFS设置，可以正常使用2.5.0版本
![image](https://user-images.githubusercontent.com/3930083/33472135-d0b11fe8-d6ab-11e7-8c42-621332cb726d.png)
![image](https://user-images.githubusercontent.com/3930083/33472143-d9faf5c4-d6ab-11e7-84db-1ad9d49656cc.png)
