### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by chenzq1019** [BuglyDevTeam/Bugly-iOS#100]
2.5.92版本编译报错
Undefined symbols for architecture arm64:
  "_rebind_symbols", referenced from:
      _BLYHookCXXExceptionThrow in Bugly(libBugly.a-arm64-master.o)
     (maybe you meant: _hl_rebind_symbols, _hl_rebind_symbols_image )
ld: symbol(s) not found for architecture arm64

**Comment by xiaocui0803** [comment]
麻烦更新2.5.93，晚些时候我们上架官网。
