### ISSUE TITLE
Xcode 14.3 需要 xcframework

### ISSUE THREAD

**Issue by lexrus** [BuglyDevTeam/Bugly-iOS#105]
Xcode 14.3 将要不支持用 Rosetta 方式运行了，Bugly 能不能更新一版 xcframework 的？
https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3-release-notes

**Comment by wangyong-numob** [comment]
同样需要，希望能更新

**Comment by a792883583** [comment]
同样需要，希望能更新+1

**Comment by xiangBiaoOne** [comment]
同样需要，希望更新+1

**Comment by LDY-CODE** [comment]
同样需要，希望更新+1

**Comment by rgmyyw** [comment]
同样需要，希望更新+1

**Comment by lexrus** [comment]
快一年了，感觉没什么希望了，换别家的吧。
