### ISSUE TITLE
2.5.0版本表现似乎是死锁的堆栈信息

### ISSUE THREAD

**Issue by dopcn** [BuglyDevTeam/Bugly-iOS#12]
cocoapods 引入，今天更新到 2.5.0，每次崩溃都会卡住所在线程，故意制造闪退可以重现，堆栈：
![screen shot 2017-12-01 at 18 07 24](https://user-images.githubusercontent.com/1253817/33477952-91d67464-d6c2-11e7-85c2-a3b8893e3e58.png)

看堆栈信息似乎是 BLYCPPExceptionTerminate() 里又抛出异常，导致在同一个线程再次进入这个方法，之前的锁还没有释放再次加锁造成死锁 

一开始引入 bugly 的时候并没有这个情况，可能是项目增加的一些内容和修改导致，不过不知道这个方法里加锁进行的操作是什么，没有办法判断可能是什么引起的

**Comment by iliYF** [comment]
你好，能麻烦提供一下故意制造崩溃复现此场景的代码片段吗？

**Comment by dopcn** [comment]
@iliYF 在我们的项目里任意 objc 的Uncaught Exception 都可以导致这个现象，故意制造只是为了测试。原因应该是我们项目里引入的某些代码或者某些设置，同样的测试方式在一个空工程中不会复现同样的卡死。所以想问的是这个方法里加锁进行的操作大概是什么，我们好从这个出发寻找一下可能的原因。

附：触发图中现象的代码
NSString *name;
NSDictionary *info = @{@"name": name};

**Comment by dopcn** [comment]
使用了FMDB?

**Comment by dopcn** [comment]
解决了，是个奇怪的问题，不是bugly的问题
https://stackoverflow.com/questions/35939491/objective-c-not-catching-exception-in-try-catch-block
