### ISSUE TITLE
bugly与aspects 共存运行即闪退

### ISSUE THREAD

**Issue by shaveKevin** [BuglyDevTeam/Bugly-iOS#16]
1.如果把aspects写在load方法中，那么运行就闪退

2.如果自己调用aspects 方法，那么运行一段时间之后闪退
`==5313==ERROR: AddressSanitizer failed to deallocate 0x20000 (131072) bytes at address 0x000151ac8800
==5313==AddressSanitizer CHECK failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-900.0.39.2/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_posix.cc:143 "(("unable to unmap" && 0)) != (0)" (0x0, 0x0)
    #0 0x106f82cef in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/var/containers/Bundle/Application/E3174B38-2EC6-4026-99C4-A34B60D2670B/HuiZhenIPhone.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib:arm64+0x56cef)`

**Comment by shaveKevin** [comment]
原因是 把方法写到了+load 里面 写到appdele 里面解决问题

**Comment by yilliam** [comment]
使用XCode(Version 10.1)，iPhone 6s真机调试代码时，开启Address Sanitizer后，在使用Bugly的情况下，App运行不久后报出同样错误地址，同样的内存大小。注掉Bugly调用后，App正常。
ERROR: AddressSanitizer failed to deallocate 0x20000 (131072) bytes at address 0x000151ac8800
