### ISSUE TITLE
出现The application did not terminate cleanly but no crash occured

### ISSUE THREAD

**Issue by PrismXX** [BuglyDevTeam/Bugly-iOS#18]
![image](https://user-images.githubusercontent.com/16411624/39516303-2469e91c-4e2f-11e8-87c3-517ed1e00ba7.png)
如图，使用的是最新的sdk

**Comment by PrismXX** [comment]
刚刚刷新报错页面，这个bug又消失了。。。什么情况- -

**Comment by renmoqiqi** [comment]
开启记录非正常退出事件配置会有这样的错误异常。指的是非正常退出事件实际上就是unix的专业术语的一个指令事件，叫做"SIGKILL"，而"SIGKILL"一般不是用户或者开发者的问题，而是[程序已经进入suspend状态、applicationDidEnterBackground已经回调的时候，由系统发出"SIGKILL"强制程序直接结束。比如用户双击home键自己杀掉
