### ISSUE TITLE
刚看到qq音乐好像有利用越狱设备来发灰度包

### ISSUE THREAD

**Issue by CodeLife2012** [BuglyDevTeam/Bugly-iOS#2]
但我点了弹出来的bugly网页根本没有反应 ？
是有bug，还是根本就不支持越狱设备灰度应用？

**Comment by szrambo** [comment]
你好，请问是咨询内测分发服务么？请联系我们的客服QQ：800014972

**Comment by CodeLife2012** [comment]
@szrambo 对怎么实现的比较感兴趣，已经大概知道了，9以后好像用处不是很大
