### ISSUE TITLE
请将podspec中source的链接更改为https

### ISSUE THREAD

**Issue by yikuo123** [BuglyDevTeam/Bugly-iOS#20]
[!] 'Bugly' uses the unencrypted http protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts in there. Please reach out to the library author to notify them of this security issue.

**Comment by 54dujianchao** [comment]
我也出现了这个问题，垃圾腾讯

**Comment by teslia** [comment]
腾讯连HTTPS证书都买不起吗？
