### ISSUE TITLE
Bugly中包含hotfix字段相关

### ISSUE THREAD

**Issue by kingsword** [BuglyDevTeam/Bugly-iOS#26]
用strings检测了下bugly，发现其中包含hotfix字段，但是bugly不是把热更新的功能去掉了么？为什么还会有这样的字段？

com.tencent.bugly.hotfix.patchstrategy
com.tencent.bugly.hotfix.patchstrategyut
com.tencent.bugly.graymixedstrategy
com.tencent.bugly.hotfix.strategy
com.tencent.bugly.hotfix.strategyut
com.tencent.bugly.grayevents
com.tencent.bugly.hotfix.patchversion
......
HotfixData

**Comment by JalenChen** [comment]
这些类是用于补丁管理，如果不需要热更新功能，请使用Crash SDK

**Comment by kingsword** [comment]
> 这些类是用于补丁管理，如果不需要热更新功能，请使用Crash SDK

然而就是用的Crash SDK...
