### ISSUE TITLE
iOS13 符号表无法解析

### ISSUE THREAD

**Issue by JockerLUO** [BuglyDevTeam/Bugly-iOS#40]
![image](https://user-images.githubusercontent.com/28944925/66700914-b7d25380-ed28-11e9-93a0-306d79ecffb6.png)

**Comment by JockerLUO** [comment]
![image](https://s2.ax1x.com/2019/10/14/uz8qC4.png)

**Comment by mqiezi** [comment]
没任何回复就关闭？不能回复下哪个版本解决了吗？解决方法~~
