### ISSUE TITLE
大佬们，内存泄露修改下啊

### ISSUE THREAD

**Issue by 2856571872** [BuglyDevTeam/Bugly-iOS#68]
![image](https://user-images.githubusercontent.com/10896490/110411080-e347a200-80c4-11eb-9755-3e1b4e20aecb.png)

**Comment by 410493897** [comment]
我也是有这个问题，大佬们解决一下

**Comment by rocky666666** [comment]
pod 'Bugly','~> 2.5.8'  已经修复

**Comment by 2856571872** [comment]
6666666



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: rocky ***@***.***&gt;
发送时间: 2021年3月18日 15:54
收件人: BuglyDevTeam/Bugly-iOS ***@***.***&gt;
抄送: 烟雨平生 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[BuglyDevTeam/Bugly-iOS] 大佬们，内存泄露修改下啊 (#68)





 
pod 'Bugly','~&gt; 2.5.8'  已经修复
