### ISSUE TITLE
符号表上传jar包报错

### ISSUE THREAD

**Issue by ChaosTong** [BuglyDevTeam/Bugly-iOS#71]
错误: 尝试打开文件buglyqq-upload-symbol.jar时出现意外错误

$ java --version
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9)
OpenJDK 64-Bit Server VM (build 15.0.1+9, mixed mode, sharing)

**Comment by ChaosTong** [comment]
macOS & Raspi 这个 jar 包都直接报错运行不了,
windows 下能用, 估计打包的人只用windows吧, 急着上传的朋友, 可以找台 windows 上传

**Comment by zhulintao** [comment]
我们这边少数几个Mac不能穿，我刚好命中。除了改用windows，Mac有解决方案吗？

错误: 尝试打开文件buglyqq-upload-symbol.jar时出现意外错误

**Comment by ChaosTong** [comment]
既然有人能用的话，从java版本上考虑吧，试着装和他们同版本的jdk试试 @zhulintao

**Comment by zhulintao** [comment]
解决了，jdk版本太高，降到jdk1.8.0就好了
![截屏2021-06-25 下午6 12 45](https://user-images.githubusercontent.com/20701000/123409611-f2ede680-d5e0-11eb-9c66-960fd027871b.png)

**Comment by cwwise** [comment]
我也遇到了，都不带测试的，离谱。

**Comment by mrrobot97** [comment]
离谱+1

**Comment by TsingYii** [comment]
离谱+1

**Comment by m8282823** [comment]
离谱+1

**Comment by huicongfu** [comment]
> 解决了，jdk版本太高，降到jdk1.8.0就好了
> ![截屏2021-06-25 下午6 12 45](https://user-images.githubusercontent.com/20701000/123409611-f2ede680-d5e0-11eb-9c66-960fd027871b.png)

感谢~搞了好久才知道这个原因

**Comment by yinfan87** [comment]
离谱+2

**Comment by Zss1990** [comment]
离谱+3
