### ISSUE TITLE
 用户输入的DSYM文件目录存在重复的文件，请去重后再执行

### ISSUE THREAD

**Issue by LinkRober** [BuglyDevTeam/Bugly-iOS#75]
dSYM文件夹里面就一个dSYM文件，和脚本自己生成的zip文件怎么，为什么一直报文件重复。eg：
```
java -jar buglyqq-upload-symbol.jar -appid xxx -appkey xxx -bundleid xxx -version xxx -platform IOS -inputSymbol ./dSYM
```

**Comment by LinkRober** [comment]
换了个方案，使用Curl工具能传上去

**Comment by fuboyou** [comment]
重复+1

**Comment by iAllenC** [comment]
+1

**Comment by LinkRober** [comment]
> 换了个方案，使用Curl工具能传上去

但是很不稳定，是不是抽风

**Comment by hujiaju** [comment]
Curl貌似也不行了，一会返回{"rtCode":50500, "msg":success}，一会儿返回{"rtcode":40404,"msg":"xxx"}
用buglyqq-upload-symbol.jar 就报：用户输入的DSYM文件目录存在重复的文件，请去重后再执行
到底该使用什么姿势呢？

**Comment by hujiaju** [comment]
> > 换了个方案，使用Curl工具能传上去
> 
> 但是很不稳定，时不时抽风

Curl貌似也不行了，一会返回{"rtCode":50500, "msg":success}，一会儿返回{"rtcode":40404,"msg":"xxx"}
用buglyqq-upload-symbol.jar 就报：用户输入的DSYM文件目录存在重复的文件，请去重后再执行
到底该使用什么姿势呢？

**Comment by li6185377** [comment]
不能对总的 dSYM 执行命名，-inputSymbol 需要指定 主target，  比如 -inputSymbol   ./X.app.dSYM/X.app.dSYM

**Comment by namo-py** [comment]
> 不能对总的 dSYM 执行命令，要把 -inputSymbol 改为指定 主target， 比如 -inputSymbol ./X.app.dSYM/X.app.dSYM

👍👍👍

**Comment by LinkRober** [comment]
> > > 换了个方案，使用Curl工具能传上去
> > 
> > 
> > 但是很不稳定，时不时抽风
> 
> Curl貌似也不行了，一会返回{"rtCode":50500, "msg":success}，一会儿返回{"rtcode":40404,"msg":"xxx"}
> 用buglyqq-upload-symbol.jar 就报：用户输入的DSYM文件目录存在重复的文件，请去重后再执行
> 到底该使用什么姿势呢？

是的，这个也用不了了。官方提供的脚本时不时的报 `存在重复的文件` 也不是每次都出错。这个很迷

**Comment by Moussy** [comment]
啥也不说先给你点个赞，下次上传我验证下

**Comment by mengxiangjian13** [comment]
> 不能对 App 总的 dSYM 执行命令，要把 -inputSymbol 参数改为主 target，简单来说 就在加一层路径，之前是 -inputSymbol ./XXX.app.dSYM ， 改为 -inputSymbol ./XXX.app.dSYM/XXX.app.dSYM

这样的话是不是说不能批量上传符号表了，只能一个一个传吗？
