### ISSUE TITLE
Bugly 存在内存泄露

### ISSUE THREAD

**Issue by iostalks** [BuglyDevTeam/Bugly-iOS#9]
![1510650482455](https://user-images.githubusercontent.com/12881129/32771665-1180c738-c8e9-11e7-8f4b-8f0a7d5fd2a8.jpg)

**Comment by TsuiOS** [comment]
startWithAppId 内存泄露

**Comment by 002and001** [comment]
bugly2.5.0还存在着内存泄漏，貌似没人处理这些issue

**Comment by JalenChen** [comment]
Duplicate of #30
