### ISSUE TITLE
buglyqq-upload-symbol.jar时出现意外错误

### ISSUE THREAD

**Issue by Jacky-LinPeng** [BuglyDevTeam/Bugly-iOS#95]
java -version
java version "18.0.1.1" 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

**Comment by xiaocui0803** [comment]
目前官网上的jar包是只支持java8的环境，这个有说明的。
