### ISSUE TITLE
升级到2.5.92后项目编译失败

### ISSUE THREAD

**Issue by XiFengLang** [BuglyDevTeam/Bugly-iOS#99]
Xcode版本： 13.2.1
Bugly版本：2.5.92       之前的2.5.91正常

编译报错： Undefined symbol: _rebind_symbols

**Comment by XiFengLang** [comment]
ld: warning: directory not found for option '-F/Users/jk/Desktop/JK/Gitlab-OKKI/xim-ios/xim/SupportingFiles/Resource/SDK/ISOpenSDKFoundation.embeddedframework'
Undefined symbols for architecture x86_64:
  "_rebind_symbols", referenced from:
      _BLYHookCXXExceptionThrow in Bugly(libBugly.a-x86_64-master.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by XiFengLang** [comment]
Showing All Messages
Directory not found for option '-F/Users/.../SupportingFiles/Resource/SDK/ISOpenSDKFoundation.embeddedframework'

Undefined symbol: _rebind_symbols

**Comment by li-jun** [comment]
我也是切换回2.5.91版本了，估计是92版本不再提供x86_64架构的编译代码了。

**Comment by li-jun** [comment]
> 我也是切换回2.5.91版本了，估计是92版本不再提供x86_64架构的编译代码了。

Architectures in the fat file: /Users/ios/Downloads/Bugly.framework/Bugly are: armv7 i386 x86_64 arm64
看了一下，是包含x86_64架构的，这可能是92版本本身的问题了。

**Comment by BinBear** [comment]
遇到同样问题

**Comment by xiaocui0803** [comment]
问题已修复，请更新到2.5.93版本，抱歉给大家带来影响。

大家有类似的紧急问题可以加我QQ：1258192191。
